version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ioannissecret 
      POSTGRES_USER: ioannis
      POSTGRES_DB: ioannisdb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations
    ports:
    - "8082:8080"
    depends_on:
    - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://ioannis:ioannissecret@db:5432/ioannisdb
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - ./hasura/migrations:/hasura-migrations
  
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
    - "8083:80"

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    environment:
      DB_HOST: "db"
